name: build payment
on: 
  push:
    branches:
      - "main"
    # paths: 
    #   - 'payment/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "16.x"
      - name: Building application
        run: |
          cd payment
          npm i -g @nestjs/cli
          npm install
          npm run build

  build-and-publish-docker:
    needs: build
    name: 'deploy payment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd payment

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ivanmds/poc_event_driven_payment:1.0.4

#   checking_approval:
#     name: checking external approval
#     if: github.event_name == 'repository_dispatch' && github.event.action == 'release_was_analysed'
#     needs: [build]
#     runs-on: ubuntu-latest
#     steps:
#       - name: checking if release wasn't approved 
#         if: github.event.client_payload.wasApproved == false
#         run: |
#           echo release wasn't approved
#           exit 1
#       - name: checking if release was approved
#         run: echo release was approved

#   deploy_prod:
#     name: 'deploy to production'
#     runs-on: ubuntu-latest
#     needs: [checking_approval]
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: main
#       - run: ls -a
#       - uses: trstringer/manual-approval@v1
#         with:
#           secret: ${{ github.TOKEN }}
#           minimum-approvals: 1
#           approvers: ivanmds
#           issue-title: "Deploying to production"
#       - run: echo 'deploy container to prod'